Truck.create(name: "E2", model: "HMV")
Truck.create(name: "E3", model: "HMV")
Truck.create(name: "E41", model: "LHS")
Truck.create(name: "E52", model: "LMTV")
Truck.create(name: "E53", model: "LMTV")
Truck.create(name: "E54", model: "LMTV")

Soldier.create(name: "Steinmetz", phone_number: "630.880.8271", rank: "e4")
Soldier.create(name: "Sosebe", phone_number: "630.880.8271", rank: "e4")
Soldier.create(name: "Ramierez", phone_number: "630.880.8271", rank: "e4")
Soldier.create(name: "Wojo", phone_number: "630.880.8271", rank: "e4")
Soldier.create(name: "Smith", phone_number: "630.880.8271", rank: "e5")
Soldier.create(name: "West", rank: "e5")
Soldier.create(name: "Avelia", rank: "e6")
Soldier.create(name: "Lynch", rank: "e5")
Soldier.create(name: "Dean", rank: "e4")
Soldier.create(name: "Cortez", rank: "e4")
Soldier.create(name: "Prado", rank: "e4")
Soldier.create(name: "Williams", rank: "e5")
Soldier.create(name: "Young", rank: "e4")
Soldier.create(name: "Reyes", rank: "e5")
Soldier.create(name: "Scrogins", rank: "e6")

Trailer.create(name: "TL100")
Trailer.create(name: "TL102")


